# Generated by Django 5.0.6 on 2026-07-26 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('industry', models.CharField(choices=[('general', 'General'), ('retail', 'Retail'), ('catering', 'Catering & Food Service'), ('services', 'Professional Services'), ('wholesale', 'Wholesale / Distribution'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], default='general', max_length=30)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
